# Generated by Django 5.0.3 on 2024-04-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('interview', 'Interview'), ('offer', 'Offer'), ('reject', 'Reject')], default='pending', max_length=20),
        ),
    ]
